name             'pbis-open'
maintainer       'Biola University'
maintainer_email 'jared.king@biola.edu'
license          'Apache 2.0'
description      'Installs and configures PowerBroker Identity Services Open Edition'
long_description 'Installs and configures PowerBroker Identity Services Open Edition'
source_url       'https://github.com/biola/chef-pbis-open'
issues_url       'https://github.com/biola/chef-pbis-open/issues'
version          '1.1.1'

depends          'chef-vault', '~> 1.1'
